### PR TITLE
Draw snake shape based on specs payload

### PR DESCRIPTION
**Pull request by avaly**

### CODE REVIEW

**Comment by balboah** [comment]
I tuned the spec to match the type on the server-side, please check it out. Also it's up in payload branch if you want to run the server locally

**Comment by avaly** [comment]
I implemented this using an earlier version of the payload structure:

``` json
{"Command": "MOVE", "Payload": {"Id": 1, "Positions": [[2, 1], [2, 2], [2, 6], [4, 6]]}}
```

**Comment by avaly** [comment]
Could you write up something on the wiki regarding how to run the server locally?

```
$ go build flow/main.go
flow/main.go:5:2: import "joonix.se/flow": cannot find package

$ go run flow/main.go
flow/main.go:5:2: import "joonix.se/flow": cannot find package
```

**Comment by balboah** [comment]
Right, I will fix that.

For now you can git clone into your `$GOPATH/src/joonix.se/flow`

Then do something like `cd $GOPATH/src/joonix.se/flow && go run flow/main.go -www=./html`

it will listen on port 5000

**Pull request closed without merging**
